{% set name = "simhash" %}
{% set version = "1.7.1" %}
{% set sha256 = "434811eb975e8888bb1e872fc8d532c3ca1b4c6475f5fb1a4456c0b2562e73c0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - simhash

about:
  home: https://leons.im/posts/a-python-implementation-of-simhash-algorithm/
  license: MIT
  license_family: MIT
  summary: 'This is a Python implementation of [Simhash](http://www.wwwconference.org/www2007/papers/paper215.pdf)'

  dev_url: https://github.com/leonsim/simhash

extra:
  recipe-maintainers:
    - nikicc
