{% set version = "1.10.2" %}

package:
  name: simhash
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/simhash/simhash-{{ version }}.tar.gz
  sha256: 6b3496ef3c48b0e38f7470e92baea2d9045164f69bcbf0f8b326bedb5d45276b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - simhash

about:
  home: https://leons.im/posts/a-python-implementation-of-simhash-algorithm/
  license: MIT
  license_family: MIT
  summary: This is a Python implementation of [Simhash](http://www.wwwconference.org/www2007/papers/paper215.pdf)

  dev_url: https://github.com/leonsim/simhash

extra:
  recipe-maintainers:
    - nikicc
