{% set version = "1.10.1" %}

package:
  name: simhash
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/simhash/simhash-{{ version }}.tar.gz
  sha256: 7cd59981fbad08bc656eb3bb8091547e5eee749302dd649019876c9c892a5868

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - simhash

about:
  home: https://leons.im/posts/a-python-implementation-of-simhash-algorithm/
  license: MIT
  license_family: MIT
  summary: This is a Python implementation of [Simhash](http://www.wwwconference.org/www2007/papers/paper215.pdf)

  dev_url: https://github.com/leonsim/simhash

extra:
  recipe-maintainers:
    - nikicc
